on:
  pull_request:
    branches:
      - main
name: unittest-prerelease
jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10']
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install nox
      run: |
        python -m pip install --upgrade setuptools pip wheel
        python -m pip install nox
    - name: Run unit tests
      env:
        COVERAGE_FILE: .coverage-prerelease-${{ matrix.python }}
      run: |
        nox -s unit_prerelease
    - name: Upload coverage results
      uses: actions/upload-artifact@v3
      with:
        name: coverage-artifacts
        path: .coverage-${{ matrix.python }}
